version: '3.1'

services:
  rails:
    build: ./rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/app_name
    links:
      - rails-mysql


  rails-mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: rails
      MYSQL_ROOT_PASSWORD: passwd